<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="customerAccountCreate" targetNamespace="http://www.colpatria.com/esb/services/customer/as/customerAccountCreate/" xmlns:esb="http://www.colpatria.com/ents/esb/MessageFormat-v1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenv11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.colpatria.com/esb/services/customer/as/customerAccountCreate/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.colpatria.com/esb/services/customer/as/customerAccountCreate/" xmlns:mrm="http://www.colpatria.com/esb/services/customer/as/customerAccountCreate/">
			<xsd:include schemaLocation="customer.accountcreate.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="customerAccountCreate_in">
		<wsdl:part element="tns:customerAccountCreateRq" name="customerAccountCreateRq"/>
	</wsdl:message>
	<wsdl:message name="customerAccountCreate_out">
		<wsdl:part element="tns:customerAccountCreateRs" name="customerAccountCreateRs"/>
	</wsdl:message>
	<wsdl:message name="customerAccountCreate_fault1">
		<wsdl:part element="tns:customerAccountCreateRs" name="customerAccountCreateRs"/>
	</wsdl:message>
	<wsdl:portType name="MBC_customerAccountCreatePortType">
		<wsdl:operation name="customerAccountCreate">
			<wsdl:input message="tns:customerAccountCreate_in" name="customerAccountCreate_Input"/>
			<wsdl:output message="tns:customerAccountCreate_out" name="customerAccountCreate_Output"/>
			<wsdl:fault message="tns:customerAccountCreate_fault1" name="customerAccountCreate_Fault"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="MBC_customerAccountCreateSOAP_HTTP_Binding" type="tns:MBC_customerAccountCreatePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="customerAccountCreate">
			<soap:operation soapAction=""/>
			<wsdl:input name="customerAccountCreate_Input">
				<soap:body parts="customerAccountCreateRq" use="literal"/>
			</wsdl:input>
			<wsdl:output name="customerAccountCreate_Output">
				<soap:body parts="customerAccountCreateRs" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="customerAccountCreate_Fault">
				<soap:fault name="customerAccountCreate_Fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="customerAccountCreate">
		<wsdl:port binding="tns:MBC_customerAccountCreateSOAP_HTTP_Binding" name="customerAccountCreateSOAP_HTTP_Port">
			<soap:address location="https://bancoColpatria/customerAccountCreate"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>