<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="customerTypeGet" targetNamespace="http://www.colpatria.com/esb/services/customer/as/customerTypeGet/" xmlns:esb="http://www.colpatria.com/ents/esb/MessageFormat-v1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenv11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.colpatria.com/esb/services/customer/as/customerTypeGet/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.colpatria.com/esb/services/customer/as/customerTypeGet/" xmlns:mrm="http://www.colpatria.com/esb/services/customer/as/customerTypeGet/">
			<xsd:include schemaLocation="customer.TypeGet.xsd"/>
		</xsd:schema>
  </wsdl:types>
  <wsdl:message name="customerTypeGet_in">
    <wsdl:part element="tns:customerTypeGetRq" name="customerTypeGetRq"/>
  </wsdl:message>
  <wsdl:message name="customerTypeGet_out">
    <wsdl:part element="tns:customerTypeGetRs" name="customerTypeGetRs"/>
  </wsdl:message>
  <wsdl:message name="customerTypeGet_fault1">
    <wsdl:part element="tns:customerTypeGetRs" name="customerTypeGetRs"/>
  </wsdl:message>
  <wsdl:portType name="MBC_customerTypeGetPortType">
    <wsdl:operation name="customerTypeGet">
      <wsdl:input message="tns:customerTypeGet_in" name="customerTypeGet_Input"/>
      <wsdl:output message="tns:customerTypeGet_out" name="customerTypeGet_Output"/>
      <wsdl:fault message="tns:customerTypeGet_fault1" name="customerTypeGet_Fault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MBC_customerTypeGetSOAP_HTTP_Binding" type="tns:MBC_customerTypeGetPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="customerTypeGet">
      <soap:operation soapAction=""/>
      <wsdl:input name="customerTypeGet_Input">
        <soap:body parts="customerTypeGetRq" use="literal"/>
      </wsdl:input>
      <wsdl:output name="customerTypeGet_Output">
        <soap:body parts="customerTypeGetRs" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="customerTypeGet_Fault">
        <soap:fault name="customerTypeGet_Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="customerTypeGet">
    <wsdl:port binding="tns:MBC_customerTypeGetSOAP_HTTP_Binding" name="customerTypeGetSOAP_HTTP_Port">
      <soap:address location="https://bancoColpatria/customerTypeGet"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>